services:
  - type: web
    name: link-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_PIN
        value: "1234"
      - key: SECRET_KEY
        generateValue: true
    plan: free
